# Messages configuration
# For color codes use "&" symbol.
messages:
  plugin-prefix: "&7[&6PassMe&7]"
  remind-register: "&2You can protect your account &8(use /register)"
  register-success: "&2Registration successful"
  login-required: "&bLogin required"
  login-hint: "&7use /login"
  login-success: "&aLogin successful"
  logout-success: "&aLogout successful"
  session-resumed: "&aYour last session has been resumed."
  wrong-password: "&cWrong password"
  session-expired: "&8Session has expired"
  too-many-fails: "&cYou've exceeded your login tries"
  password-changed: "&aPassword has been changed"
  only-for-players: "&cThat command can be executed only by players"
  login-usage: "&aUse: /login <password>"
  register-usage: "&aUse: /register <password> <repeat_password>"
  register-console-usage: "&cUse /register <player_name> <password>"
  change-password-usage: "&aUse: /changepassword <old_password> <new_password>"
  change-password-console-usage: "&aUse: /changepassword <player_name> <new_password>"
  missing-registration: "&aFor that command you need to be registered"
  login-time-exceed: "&cLogin time has been exceeded"
  registration-required: "&cOnly registered player can join this server.\nContact with administrator"
  registration-hint: "&7 use /register"
  registration-time-exceed: "&cRegistration time has been exceeded"
  registration-must-be-set: "&bRegistration required"
  player-not-found: "&cUnable to find player, or it not registered"
  passwords-not-equals: "&cPassword aren't equals"

# Sessions configuration
sessions:
  # Whether is sessions enabled
  is-enabled: true
  # Expiration time for each session (in seconds)
  expiration-time: 86400

# Login configuration
login:
  # Max tries to enter password
  max-tries: 3
  # Max login grace time (in seconds)
  login-time-limit: 45
  # Max registration grace time (in seconds)
  registration-time-limit: 60
  # Auth mode.
  #   "strict" - all player should set up password
  #   "strong" - player with specified below permission should set up password
  #   "passive" - players can set up their password when they want
  mode: "strict"

# Misc rules
rules:
  # Only player with password can join
  registration-required: false
  # Players with those permissions should set up password,
  # when login mode is "strong"
  strong-mode-permissions:
    - ""
  # Allowed command while player in auth session
  # Note: do not remove: /login, /l commands from that list
  # otherwise players will not able to log in.
  allowed-command-during-login:
    - "/login"
    - "/l"
    - "/passme"
    - "/pm"